redux-observable/redux-observable

package.json

chore(package): update babel-register to version 6.9.0

---

README.md
examples/basic/json-server/db.json
examples/basic/package.json
examples/basic/server.js
examples/basic/src/actions/index.js
examples/basic/src/index.js
examples/basic/src/reducers/index.js
examples/basic/src/store/configure-store.js
examples/basic/webpack.config.js
package.json

I just want to share a few things that I found useful:
1) `npm install ` at project root failed for me, when running the basic demo, with a file not found error for redux-observable, I don't know why.  I ended up just doing `npm link`.
2) Added [JSON Server](https://github.com/typicode/json-server) to support quick mocking of ajax calls and altered demo to use it.
3) Added support for [Redux DevTools](https://github.com/gaearon/redux-devtools)
If any of these are useful, I can do individual PRs.

Possible enhancements to the demo

---

docs/recipes/WritingTests.md

It's not used anywhere so I guess it's unnecessary...

[DOC] Remove unused action$ Subject in test example

---

docs/recipes/WritingTests.md

Move `store = mockStore()` to `beforeEach(...)`.

docs(WritingTests.md): Fix mockStore for each case

---

docs/SUMMARY.md
docs/basics/SUMMARY.md

Couldn't help myself while reading docs.

chore(docs): Typo/grammar fix in SUMMARY.md

---

index.d.ts

added explicit return type definitions to life and ofType member functions within ActionsObservable class (github issue #96)

added explicit return type definitions

---

docs/api/EpicMiddleware.md

fix typo/wording

---

docs/basics/Epics.md

- Update JSBin example as the current one is broken (besides the code change, the example is currently not rendering, because`Rx.js` url is wrong in the HTML)

Fix "increment if odd" epic example

---

docs/recipes/ErrorHandling.md

Hello,
I just remove extra word. Nothing special.

remove extra 'and'

---

docs/basics/Epics.md

Fix broken link to redux-sage

---

docs/recipes/Cancellation.md

This comes up commonly enough on Gitter

docs(Cancellation): example for racing between two streams for cancellation

---

docs/basics/Epics.md
docs/recipes/Cancellation.md
docs/recipes/ErrorHandling.md

docs(ajax): Include import statements for ajax.getJSON usage

---

docs/basics/Epics.md

Fix typo in Epics.md

---

docs/recipes/Cancellation.md

doc(cancellation): fix rxjs race link

---

index.d.ts
package.json
test/typings.ts

Also made the typings test more strict, disallowing implicit any

Dependencies can now be `any` and is optional

---

docs/recipes/InjectingDependenciesIntoEpics.md

docs(InjectingDependenciesIntoEpics.md): Missing destructuring of action to get payload

---

README.md

doc(demo): Add Ember.js Demo

---

examples/redux-observable-shopping-cart/.babelrc
examples/redux-observable-shopping-cart/.gitignore
examples/redux-observable-shopping-cart/README.md
examples/redux-observable-shopping-cart/index.html
examples/redux-observable-shopping-cart/js/actions/index.js
examples/redux-observable-shopping-cart/js/components/App.js
examples/redux-observable-shopping-cart/js/components/Cart.js
examples/redux-observable-shopping-cart/js/components/CartItem.js
examples/redux-observable-shopping-cart/js/components/Product.js
examples/redux-observable-shopping-cart/js/components/ProductItem.js
examples/redux-observable-shopping-cart/js/components/ProductList.js
examples/redux-observable-shopping-cart/js/epics/index.js
examples/redux-observable-shopping-cart/js/main.js
examples/redux-observable-shopping-cart/js/reducers/cart.js
examples/redux-observable-shopping-cart/js/reducers/index.js
examples/redux-observable-shopping-cart/js/reducers/products.js
examples/redux-observable-shopping-cart/js/services/index.js
examples/redux-observable-shopping-cart/js/services/products.js
examples/redux-observable-shopping-cart/package.json
examples/redux-observable-shopping-cart/webpack.config.js

docs(examples): porting of the redux saga shopping cart example

---

index.d.ts

Add EPIC_END type

---

docs/Troubleshooting.md

docs(troubleshooting): Side effects with subscribe

---

README.md

Link to xstream adapter

---

src/ActionsObservable.js

fix(ofType): don't depend on letProto as it has issues in UMD builds

---

docs/Troubleshooting.md

Fixing typo in troubleshooting

---

README.md

docs(examples): Add Angular2+ example

---

index.d.ts

fix(typings): Fix generics in ofType type definition

---

docs/recipes/ErrorHandling.md

I noticed that the indentation was wonky (mix of tabs and spaces, not aligned), so I
fixed that to be two spaces at every level.
*Update: removed imports per discussion below*

doc(Error Handling): Fix indentation

---

docs/basics/Epics.md

As described in the oryginal link: https://github.com/ReactiveX/rxjs/blob/master/doc/lettable-operators.md

docs: Pipeable

---

.eslintrc

Fix eslint deprecation warning

---

src/createEpicMiddleware.js
src/utils/console.js
test/createEpicMiddleware-spec.js

I ran into #389 and the symptoms were pretty difficult to diagnose. This PR adds a warning for anybody making the same mistake in the future.

Add a warning for #389

---

docs/Troubleshooting.md

docs(Troubleshooting): change lettable to pipeable

---

MIGRATION.md

otherwise the state wont ever update for future actions like it should. Fixes #467
Thanks to @wmaurer for noticing!

docs(MIGRATION): withLatestFrom(state$) without take(1)

---

test/StateObservable-spec.js

Add test to prove the StateObservable `state$` works as expected when operators are applied. I fixed a bug in a previous PR that I forgot to commit/test/and comment on where applying operators would cause duplicate subscriptions to the state subject internally causing the piped over `state$` to emit once for every operator you applied to it. https://github.com/redux-observable/redux-observable/pull/498/files#diff-6ab7619f27ac69fee16660f002f9b23bL18
Also, at least for now it's intentional that StateObservable does _not_ provide a custom `lift()` so when operators are applied you lose the `state$.value` property. This may change in the future, but it seems like we'd want to no longer do distinct checks in StateObservable then because it would be surprising if lifted versions also did them. …

test(state$): test that state$ with operators works as expected

---

docs/Troubleshooting.md
docs/recipes/HotModuleReplacement.md

docs(all): Troubleshooting + Hot module replacement docs update for 1.0

---

docs/basics/Epics.md
docs/recipes/InjectingDependenciesIntoEpics.md
docs/recipes/WritingTests.md

Took an quick stab at explaining marble diagram testing, though for the most part I'd like to defer to the RxJS official docs since it's mostly just testing RxJS code.
Grammar police welcome.

marble diagram testing

---

docs/api/combineEpics.md

doc(combineEpics): add info about combineEpics epics order

add info about combineEpics order

---

docs/recipes/ErrorHandling.md

fixed missing comma
- [ x] I have read the [Contributor Guide](https://github.com/redux-observable/redux-observable/blob/master/CONTRIBUTING.md)
- [x ] My commit messages are in [conventional-changelog-standard](https://github.com/redux-observable/redux-observable/blob/master/CONTRIBUTING.md#sending-a-pull-request) format.

docs(example): fixed missing comma in ErrorHandling.md

---

MIGRATION.md

Fix typo in MIGRATION.md

---

examples/redux-observable-shopping-cart/README.md

I've added the build steps description to the 'Redux Observable shopping cart' example.

docs(examples): added build steps to the shopping cart examples README

---

docs/recipes/WritingTests.md

Addresses https://github.com/redux-observable/redux-observable/issues/638

docs(writing-tests): update marble testing link

---

docs/recipes/WritingTests.md

Update marble testing documentation link

---

docs/basics/SettingUpTheMiddleware.md

docs(combineEpics): add global error handling docs

---

.npmrc
package-lock.json
package.json

* ~~remove extraneous non-null assertion (TypeScript complained about this)~~ old code was correct
* add package-lock.json
* add tslib to devDeps (build failed because peerDeps aren't installed by default)
Cc/ @csvn

chore(build): add package-lock.json,  add tslib to devDeps

---

src/operators.ts

- [X ] I have read the [Contributor Guide](https://github.com/redux-observable/redux-observable/blob/master/CONTRIBUTING.md)
- [X ] My commit messages are in [conventional-changelog-standard](https://github.com/redux-observable/redux-observable/blob/master/CONTRIBUTING.md#sending-a-pull-request) format.

Change ofType typing

---

docs/basics/Epics.md

Minor typo in the Basics/Epics page

---

.eslintrc
src/operators.ts
test/operators-spec.ts

closes https://github.com/redux-observable/redux-observable/issues/607

Add warning for nullsy keys in ofType

---

docs/basics/SettingUpTheMiddleware.md

docs(middleware): Highlight code in "Adding global error handler"

---

docs/basics/Epics.md
docs/recipes/Cancellation.md
docs/recipes/ErrorHandling.md
package-lock.json

These have been broken due to that I no longer pay for a jsbin pro account.

docs: remove broken jsbin embeds

---

docs/Troubleshooting.md

 docs(README): Fix mis-typo in Troubleshooting

---

.eslintignore
.github/workflows/ci.yml
package.json

I figured out it would be a good idea to use Github Actions:
- better integration with PR & Github UI overall
- one place to manage everything
We needed to fix that Travis CI anyway

Setup GitHub actions

---

README.md

docs: rxjs@7 compatiblity issue

---

package-lock.json
package.json
src/createEpicMiddleware.ts

with this it seems to work fine in my template https://github.com/evertbouw/vite-template-redux-observable

bump redux

---

docs/recipes/WritingTests.md

docs: fix dead link in testing documentation
