redux-observable/redux-observable

examples/basic/webpack.config.js
This will let us actually test against the example apps without needing to rely on only the published version. I tried using `npm link` but it had the same duplicate rxjs problem.
=> refactor(examples): use repo codebase of redux-observable instead of node_module

package.json
eslint/eslint#6158 is the bug.
This fixes #14 until we can upgrade.
=> chore(devDependencies): lock eslint to v2.9.0 until upstream bug is fixed

index.d.ts, package.json, test/typings.ts
Here's an attempt at providing typings for (#12).  There are a number of different ways of doing typings, I took the approach that seemed easiest.  I would be happy to modify the typings into alternate styles, or configurations as I made a lot of assumptions. 
- adds a new `index.d.ts` file which has the typings
- adds a `typings` property in `package.json` which points to `index.d.ts`
- adds a `test/typings.ts` file which attempts to use the typings
- adds an `npm run clean` task to remove `lib` and `temp`
- adds an `npm run test_typings` task to encapsulate the typescript test command
- adds `rimraf` and `typescript` as `devDependencies`
- updates `.gitignore` to exclude intelliJ files
- modifies `npm run test` so that it executes the TypeScript test
=> Adds TypeScript typings, fixes #12

src/reduxObservable.js, test/reduxObservable-spec.js
Fixes #8 
Basically, instead of the middleware just passing emitted actions to _the next middleware_ we instead dispatch it to the store, which allows async action streams to emit other async actions (aka thunkservables), as well as allows recursive behavior via the `ActionsObservable`.
=> feat(reduxObservable): allow async streams to emit other async actions

examples/basic/server.js
I'm lazy and I want to be able to click a link in my terminal (iTerm 2) when I run an example. This makes it so I can do that.
=> docs(examples): Add clickable `localhost` link

src/ActionsObservable.js, test/ActionsObservable-spec.js
This adds a feature that allows to filter by multiple action types:
```
actions.ofType('ACTION_1', 'ACTION_2', 'ACTION_3')
```
=> feat(ofType): now accepts multiple types to filter for

package.json
Hi there,
I noticed that `index.d.ts` is missing from the files inside the `package.json`. This causes some inconvenience when using TypeScript, because you can not just `import` the package. TypeScript won't find the module ...
As a workaround you can require it (when using webpack):
```ts
const reduxObservable = require('redux-observable').reduxObservable;
```
But types will still be missing.
When adding the `index.d.ts` to the installed package everything works fine :)
This patch adds the `index.d.ts` to the `files` property.
Thx for open sourcing this plugin ❤️ 
---
**tl;dr** Adding the `index.d.ts` to the `files` property of the `package.json` will make the module work with TypeScript better.
=> Publish TypeScript definition files

examples/basic/src/actions/index.js
"automatically dispatch" is misleading/confusing. This event is dispatched because `dispatch(fetchUser())` is called elsewhere-- merely returning an action object from `.map` function does not cause the action to be dispatched.
=> Update example comments

index.d.ts
Since 9027d1c the `ofType` method allows to specify multiple action types for comparison.
Adjusted TypeScript typings accordingly.
=> fix(typings): `ofType` accepts multie keys

examples/basic/src/components/Example.js
Wrapping in dispatch is what the second argument to dispatch does if passed an object, no need to do it manually
=> Simplify dispatchToProps in example

.eslintrc, .gitignore, package.json, webpack.config.babel.js
To avoid examples [like in this comment](https://github.com/redux-observable/redux-observable/issues/47#issuecomment-227593746) (sorry ;-))
Let's just publish redux-observable on [npmcdn](https://npmcdn.com)
All this project needs is umd versions at `dist` folder in npm.
So it will be avalable after `npm version patch; npm publish` at 
`https://npmcdn.com/redux-observable@latest/build/redux-observable.js`
`https://npmcdn.com/redux-observable@latest/build/redux-observable.min.js`
And can be accessed via global `ReduxObservable` var. At `jsbin` and similar playgrounds.
=> npmcdn support

index.d.ts, package.json, src/combineDelegators.js, src/combineEpics.js, src/createEpicMiddleware.js, src/index.js, test/ActionsObservable-spec.js, test/combineEpics-spec.js, test/createEpicMiddleware-spec.js, test/typings.ts
BREAKING CHANGE: We are deprecating thunkservables in favor of the new "epic"-style. Now, creating the middleware is done with `createEpicMiddleware(rootEpic)` instead of `reduxObservable(rootEpic)` and `combineDelegators()` has been renamed `combineEpics()`. See the brand new gitbook documentation (landing soon in #66) for more details on Epics.
=> deprecate thunkservables and rename things to Epic

index.d.ts, test/typings.ts
fixes #69
@vire if you get a chance, could you confirm these new typings are good? I don't have any apps that use both TS and redux-observable yet. (though we do have a basic test of the typings included)
=> fix(TypeScript type definition): Add combineEpics(), provide more accurate type info for others

docs/basics/Epics.md
I looked for better embed solutions (that don't require a ton of setup) but couldn't find any. If someone has any recommendations on cleaner code embeds, please do let me know or even better PR 😍 
jsbin supports custom CSS styling (we could remove all the extraneous panels and fix line wrapping, etc) but it's only for paid customers and I am not.
=> docs(Epics): Add embedded JSBin examples in the Epics docs

docs/basics/Epics.md, package.json, src/EPIC_END.js, src/createEpicMiddleware.js, src/index.js, test/createEpicMiddleware-spec.js, test/typings.ts
**NOTE: I accidentally pushed an older version of [this to master days ago](https://github.com/redux-observable/redux-observable/commit/a8f458d1bf8db92c59a3e590869410e9ad73bf83) so #YOLO....part of this has already shipped. We can always revert, so it's not set in stone though.**
I'm still not convinced that using this is 100% safe, since Epics _may_ contain forms of state. There may be edge cases where losing that state causes the app to be in a bad state. For the most part that sort of state belongs in the store anyways, but this is likely not always obvious and there may be cases of ephemeral state that _should_ be in your Epic; after all, things like `Observable.ajax()` maintains internal state while the request is in-flight. Thinking we'll release it anyway and find out in practice …
=> feat(replaceEpic): Added middleware method to replace the root Epic.

README.md, docs/FAQ.md, src/createEpicMiddleware.js, test/createEpicMiddleware-spec.js
This allows us to support RxJS v4 via https://github.com/redux-observable/redux-observable-adapter-rxjs-v4
An adapter is an object that has two properties, `input` and `output`.
```js
const adapter = {
input: action$ => convertItSomeHow(action$),
output: action$ => convertItSomeHow(action$)
};
```
The input function is provided the original v5 `ActionsObservable` and the result you return is then provided to all of your Epics.
The output function is invoked for each Epic, provided with the output of that Epic. The result you return is expected to be RxJS v5 compliant; anything that `Observable.from` works on so that includes `stream[Symbol.observable]()`.
We strongly believe people should switch to v5, but we realize that not everyone has the immediate cycles to do so, or have issues …
=> feat(Adapters): Adds support for Epic input/output adapters.

.gitignore, index.d.ts, package.json, test/typings.ts, typings.json
Based on discovery and conversation of this issue on Gitter: https://gitter.im/redux-observable/redux-observable
You will now can pass in the expected shape of redux actions
```ts
interface FluxStandardAction {
type: string | symbol | any;
payload?: any;
error?: boolean | any;
meta?: any
}
const rootEpic = combineEpics<FluxStandardAction>(epic1, epic2);
const epicMiddleware = createEpicMiddleware<FluxStandardAction>(rootEpic);
// later
// types/generics inside epics can be inferred automatically!
const someEpic = (action$, store) =>
action$.ofType(SOMETHING)
.map(({ payload }) => ({
type: ELSE,
payload
}));
```
Or of course you can use `any` by just not providing them
```ts
const epicMiddleware = createEpicMiddleware(rootEpic);
```
Cc/ @SethDavenport
=> fix(typings): Add generics so developer defines what redux Actions look like

src/ActionsObservable.js, test/ActionsObservable-spec.js
Currently it's a little verbose to create a stream of actions, which happens a lot for testing but is also used in our experiments with "forking" short-lived instances of Epics.
```js
const input$ = Observable.of(...actions);
const action$ = new ActionsObservable(input$);
```
```js
const action$ = ActionsObservable.of(...actions);
```
Closes #98
=> feat(ActionsObservable.of): Added support for ActionsObservable.of(...actions)

test/ActionsObservable-spec.js
I'm guessing this is what the test was intended for, to send multiple actions through and make sure they come out on the other side.
=> fix(test): feed multiple actions through

docs/FAQ.md, package.json, src/createEpicMiddleware.js, test/ActionsObservable-spec.js, test/createEpicMiddleware-spec.js
BREAKING CHANGE: Support for thunkservables to be removed, replaced by Epics. After this, you may now use redux-thunk in tandem with redux-observable.
I need to update the FAQ page before merging this, going to make a new entry for http://redux-observable.js.org/docs/FAQ.html#why-were-thunkservables-removed
Closes #13 as well.
Cc/ @blesh
=> refactor(thunkservables): Removed support for thunkservables

src/createEpicMiddleware.js
If you aren't familiar, a BehaviorSubject will "cache" the last value and emit it to anyone who subscribes any time after. This is unlike a regular Subject, which is just a simple hot stream--if you 'next()' something on it, only existing subscriptions receive it, not future ones.
In the case of createEpicMiddleware, using BehaviorSubject was just easier to read but came at the expense of depending on it, which I think we can do without.
=> refactor(createEpicMiddleware): remove need to import/use BehaviorSubject

src/combineEpics.js, test/combineEpics-spec.js
which means now you can now easily inject dependencies to all your epics:
```js
// given epics like this
const epic1 = (action$, store, api) => {
// access to API here!
};
```
```js
import * as api from './api/location';
// inject API into all epics as third arg
const rootEpic = (...args) => combineEpics(epic1, epic2)(...args, api);
```
which makes it easier to test:
```js
const fakeApi = {
fetchSomething: () => Observable.of('fake response')
};
epic1(action$, fakeStore, fakeApi);
```
We may provide this functionality as an option to the middleware at some point since this composition may not be immediately obvious to people.
```js
// HYPOTHETICAL ONLY
createEpicMiddleware(rootEpic, { dependencies: [api] });
```
=> feat(combineEpics): combineEpics() now transparently passes along all arguments

package.json
fixes #127
Upstream webpack-rxjs-externals change: https://github.com/jayphelps/webpack-rxjs-externals/pull/1
Cc/ @blesh 
(it was already matching under our semver range, but bumping to reduce likelyhood of local caching of incorrect older lib and have a clear trace back to the fix)
=> fix(UMD): bump webpack-rxjs-externals to correct UMD generation

docs/Troubleshooting.md, docs/basics/SettingUpTheMiddleware.md, examples/navigation/configureStore.js
The extension API was changed and [`window.devToolsExtension` is being deprecated](https://github.com/zalmoxisus/redux-devtools-extension/issues/220). No need for `window.devToolsExtension.updateStore` workaround anymore.
Fixes #81.
=> chore(examples & docs): Change deprecated Redux DevTools extension enhancer

docs/basics/Epics.md
=> TRIVIAL CHANGE - add semicolon for the contraction of "it is" in Epics readme

src/combineEpics.js, src/createEpicMiddleware.js, test/combineEpics-spec.js, test/createEpicMiddleware-spec.js
Provides a more descriptive error when someone accidentally doesn't return something from their epics
```js
const someEpic = () => {
action$.ofType(SOMETHING).etc(); // whoops! forgot to return the stream!
};
```
Someone may ask why we don't try and check whether what they returned is an Observable e.g. `output instanceof Observable`. The reason is that we support any stream-like thing that RxJS supports, which is Observable, an array, an iterable/generator, or object which has `Symbol.observable` property. [see here](https://github.com/ReactiveX/rxjs/blob/master/src/util/subscribeToResult.ts). I think checking for this exhaustive list is excessive, because RxJS itself will check and error too (assuming it's not undefined, which is what we're protecting against now)
I'll try and update …
=> chore(errors): detect epics which do not return anything

test/createEpicMiddleware-spec.js
The async test was not even being tested at all, it also had bug calling on an in-existing method. This PR addresses that. Discovered this when rewriting to TypeScript. Related [issue](https://github.com/kulshekhar/ts-jest/issues/45).
=> fix test that was not properly tested

src/ActionsObservable.js, test/ActionsObservable-spec.js
Will rebase commits to satisfy changelog standard in a bit, reading the contributing guide right now...
=> Provide ActionsObservable.from()

index.d.ts
- [X ] I have read the [Contributor Guide](https://github.com/redux-observable/redux-observable/blob/master/CONTRIBUTING.md)
- [X ] My commit messages are in [conventional-changelog-standard](https://github.com/redux-observable/redux-observable/blob/master/CONTRIBUTING.md#sending-a-pull-request) format.
When using TypeScript, you will be able to use any adapter
without TypeScript compiler complaining about wrong signature of call target.
=> fix(typings): Enable second parameter for the createEpicMiddleware

package.json
This PR is completing existing PR https://github.com/redux-observable/redux-observable/pull/118 by including couple of changes
- bump up typescript dependencies to latest
- update type definition packages by using @types instead of `typings` .
=> chore(package): update type definition packages

docs/basics/SettingUpTheMiddleware.md
A trivial change in the documentation - an import was missing.
=> Documentation: added the missing import for 'combineReducers'

examples/navigation/containers/ReposByUser.jsx
@gusvargas - was this meant to do a query based on the `user` from the `nextProps` if the old props didn't match?
=> docs(navigation-example): request via nextProps

index.d.ts, package.json, test/typings.ts, typings.json
Closes #172
Also includes a couple of TypeScript-related fixes:
* redux now includes its own types, so @types/redux isn’t needed
* typings.json isn’t used anymore
=> fix(typescript): adds store type to Epic

README.md, package.json
BREAKING CHANGE:
RxJS v5 non-beta (e.g. 5.1.0) is now required. Upgrading from rxjs 5
beta to latest should be easy in most cases.
=> chore(rxjs): update rxjs to v5 non-beta

package.json, webpack.config.babel.js
[webpack-rxjs-externals API changed](https://github.com/jayphelps/webpack-rxjs-externals/pull/2) slightly, this upgrades it and our externals to the new format.
=> chore(build): upgrade to webpack2, webpack-rxjs-externals@1.0.0

index.d.ts, test/typings.ts
I try to use API injection epic pattern that like https://github.com/redux-observable/redux-observable/issues/84#issuecomment-236042600 and #163.
But current typing is not accept `combineEpics` with extra argument epics.
=> fix(typings): Add combineEpics overload for custom Epic signatures

index.d.ts, test/typings.ts
Update TypeScript types to v0.14
- 0.14 Added `dependencies` to the options of `createEpicMiddleware`. Added them to the typings and added it to the tests.
If you want some more strict typings let me know.
---
=> fix(typings): Add dependencies to middleware options.

index.d.ts
=> fix(typings): lift now uses correct return type, instead of `any`

docs/api/createEpicMiddleware.md
I found lack `createEpicMiddleware` options argument and fix it
=> docs(createEpicMiddleware) Fix title function argument

docs/recipes/Cancellation.md
Fix typos:
- Corrected various grammatical errors (e.g. "more clean")
Clarify wording:
- Minor fixes throughout the _Cancel And Do Something Else_ section
- Elaborated upon quoted section re: idiomatically repurposing cancellation actions
=> docs(cancellation): fix typos, clarify wording

README.md
Lately I research the redux-observable and I find that it lack the Chinese Docs.
As we all know, the Chinese Docs lead the rxjs community to be stronger than ever.
So I add Chinese localization for the redux-observable . Hope this can help in anyway.
=> docs:add Chinese localization

index.d.ts, test/typings.ts
This PR is a *draft* and should be considered as an extension to the discussion started in #231.
Feedback is mandatory ;)
Added a dependency generic type to typings.
The type defaults to `any` for backwards compatibility.
=> feat(typings): added dependencies generic type

index.d.ts, test/typings.ts
By making the type parameter `T` extend `Action` (i.e. telling the compiler that `T` has a `type` field),
it's possible to type `ofType()` correctly using lookup types.
=> Fix typing of `ofType`

examples/redux-observable-cancellable-counter/.babelrc, examples/redux-observable-cancellable-counter/.gitignore, examples/redux-observable-cancellable-counter/README.md, examples/redux-observable-cancellable-counter/index.html, examples/redux-observable-cancellable-counter/js/actionTypes.js, examples/redux-observable-cancellable-counter/js/components/Counter.js, examples/redux-observable-cancellable-counter/js/epics/index.js, examples/redux-observable-cancellable-counter/js/main.js, examples/redux-observable-cancellable-counter/js/mainWithSaga.js, examples/redux-observable-cancellable-counter/js/reducers/counter.js, examples/redux-observable-cancellable-counter/js/reducers/index.js, examples/redux-observable-cancellable-counter/js/sagaMonitor/index.js, examples/redux-observable-cancellable-counter/js/sagas/index.js, examples/redux-observable-cancellable-counter/package.json, examples/redux-observable-cancellable-counter/webpack.config.js
I've ported the "redux saga cancellable counter example".
The porting is not 1:1 in terms of middleware adaptations, as I needed to use an extra action. I kept the original saga and the redux saga dependencies as well, so that an user could easily swap the 2 flavours of the examples if he wants to in the `webpack.config.js`. 
If you think this could be misleading I could remove the redux saga part.
Thank you for this fantastic project!
=> docs(examples): porting of the redux saga cancellable counter example

src/createEpicMiddleware.js, test/createEpicMiddleware-spec.js
=> feat(EpicMiddleware): warn about improper use of dispatch function

docs/basics/Epics.md, src/createEpicMiddleware.js, src/utils/console.js, test/createEpicMiddleware-spec.js
The ability to call `store.dispatch()` inside your Epics was originally provided as an escape hatch, to be used rarely, if ever. Unfortunately in practice we've seen a large number of people using it extensively; there has even been popular tutorials teaching it as how you use redux-observable. Instead, Epics should emit actions through the Observable the Epic returns, using idiomatic RxJS.
```js
const somethingEpic = (action$, store) =>
action$.ofType(SOMETHING)
.switchMap(() =>
ajax('/something')
.do(() => store.dispatch({ type: SOMETHING_ELSE }))
.map(response => ({ type: SUCCESS, response }))
);
```
```js
const somethingEpic = action$ =>
action$.ofType(SOMETHING)
.switchMap(() =>
ajax('/something')
.mergeMap(response => Observable.of(
{ type: SOMETHING_ELSE },
{ type: SUCCESS, …
```
=> fix(store.dispatch): Calling `store.dispatch()` directly in your Epic is now deprecated

src/operators.js, test/operators-spec.js
The actionCreators you make with redux-actions implement their own
toString, which means you don't have to keep track of action types at
all. Before this commit, you need to:
```
ofType(myActionCreator.toString())
```
In order to get this to work as expected. As of this commit, you can:
```
ofType(myActionCreator)
```
Closes: #192
=> feat(ofType): integration with redux-actions.

docs/basics/Epics.md
lotssssss of people come up with their own `.filter()` variant for this, even though it's always supported it but wasn't documented.
=> docs(ofType): clarify that `ofType` is variadic

index.d.ts
addition of a narrowing `ofType()` overload.
allows for behavior such as `action$.ofType<SomeNarrowAction>(someType);`
=> feat(ofType): typed overload (#312)

package.json
A PR to loosen the `peerDependencies` in `redux-observable`. See #358 for further details.
Closes #358.
=> feat(dependencies): Loosen peerDependencies

src/createEpicMiddleware.js, test/createEpicMiddleware-spec.js
=> Always log reducers exception #263 

index.d.ts, test/typings.ts
- change type parameter
- ofType
- Epic
- EpicMiddleware
- createEpicMiddleware
- combineEpics
- add test case to typings.ts
=> fix(typings): More correct Epic and ofType type refinement (#392)

docs/Troubleshooting.md, index.d.ts, package.json, test/typings.ts
- adds Typescript docs to troubleshooting
- enables strict mode for TS test
- covers proper type narrowing within TS tests
Closes #382
=> typings: make lettable ofType properly narrow action type

.babelrc, gulpfile.babel.js, package.json
`babel-preset-es2015` has been [deprecated](https://babeljs.io/env) in favour of `babel-preset-env` quite a long time ago.
=> Use babel-preset-env instead of es2015

docs/recipes/WritingTests.md
Current link point to `http://redux.js.org/docs/recipes/WritingTests.html` resulting in Page not Found. Updated to `https://redux.js.org/recipes/writing-tests`
=> docs(WritingTests): Fix Link to Redux Test Page

package.json, webpack.config.babel.js
This needs https://github.com/jayphelps/webpack-rxjs-externals/pull/8 before it can be merged (build will break because of it) but otherwise I believe is ready and correct.
After this is merged I'll be releasing 1.0.0-alpha of redux-observable, with the plan being that it only supports v6 and v6 style imports. Whether the old compatibility imports work or not is not yet clear as that stuff is still in flux. Latest word is that rxjs-compat might be included by default in v6 with deprecation warnings. If you don't know what any of that is, the tl;dr is that ideally you will use the new rxjs import locations but you might be able to still use the old paths for a time.
This is a follow up to #403
=> chore(rxjs): Support rxjs v6 UMD builds

index.d.ts
I had to add this to use it in my own project, so I figured I would share.
=> fix(typings): Update type of Epic to add state$

package.json, scripts/publish.sh
I correctly published 1.0.0-alpha.0 as the `next` dist-tag but accidentally published alpha.1 as `latest` (the default). I've since corrected this, but hopefully this PR will help prevent that from happening again.
=> chore(publishing): Support dist-tag publishing with our 'shipit' scripts

package.json
it gets added automatically by gitbook sometimes even though it was already listed as a dev-dep. I have never been able to tell when or how, it just shows up as a dep from time to time and I usually manually remove it, but for some reason I committed it last year. I can't recall why I gave in, but it's potentially an unnecessary headache for people who's companies require they audit and approval all dependencies; which is why I classified this as a fix(deps).
https://github.com/redux-observable/redux-observable/commit/cd4463006ae132966ffd9e96aa53bcd32b205724#commitcomment-28489406
=> fix(deps): gitbook-plugin-github is no longer listed as a normal dependency

package.json
Just to make sure we're testing against the latest v6 version and no longer beta/rc/etc
For now we'll leave the peerDep to >=v6-beta.0
=> Upgrade internal rxjs devdep version to v6-final

src/combineEpics.js, test/combineEpics-spec.js
Combined functions always return `<anonymous>` which is not very useful. This Commit updates the name of the combined epics to the following:
> combineEpics(epic1, epic2)
=> Combined function name

src/StateObservable.js, test/StateObservable-spec.js
(e.g. prevValue !== nextValue) It still emits the current state immediately on subscribe regardless, as it did before, similar to BehaviorSubject. Closes #497
=> feat(state$): state$ now only emits subsequent values if the state shallowly is different

package.json, test/createEpicMiddleware-spec.js, test/initAction.d.ts, test/initAction.js, test/typings.ts
Bumped version number and fixed tests
=> chore(redux): Finalize Redux 4 support

src/createEpicMiddleware.js, test/createEpicMiddleware-spec.js
See https://redux-observable.js.org/MIGRATION.html#setting-up-the-middleware
This should help people who happen to not read the migration guide or release notes.
=> feat(rootEpic): an error is now thrown if you provide your root Epic to createEpicMiddleware

src/StateObservable.js, src/createEpicMiddleware.js, test/StateObservable-spec.js, test/createEpicMiddleware-spec.js, test/typings.ts
I found that state$ was actually skipping the initial first state and in fact because of the way redux v4 works and our new `epicMiddleware.run(rootEpic)` API
BREAKING CHANGE: state$ now receives the initial state
BREAKING CHANGE: previously the second argument to your epics was a "lite" version of the redux store with store.dispatch() and store.getState(), however this has been replaced with a stream of a state$ in v1.0.0 of redux-observable and the old methods were deprecated with warnings in previous alpha versions. This release removes them entirely. See https://redux-observable.js.org/MIGRATION.html
=> fix(state$): initial state is no longer skipped, and remove deprecated store APIs

src/combineEpics.js
Reported by someone on Discord, relayed by @evertbouw. On React Native Android it appears the JS runtime enforces the fact that Functions are supposed to have their `name` property be readonly, by throwing an exception. So in those cases we just catch the error and ignore it since I'm not aware of any other way to test whether it's supported or not. I'm also not sure how we could unit test this behavior either.
=> fix(combineEpics): combineEpics no longer errors on React Native Android because of readonly `name`  prop setting

.babelrc, package.json
AFAICT it's not needed for us anymore. ~I believe~ I thought this is what is causing #513 to fail with the new webpack but turns out it's not. Regardless something to do.
=> chore(babel): remove unnecessary transform-es2015-modules-commonjs

src/createEpicMiddleware.js, test/createEpicMiddleware-spec.js
This PR is against the `stable` branch (tracking 0.18.0), not `master` (tracking 1.0.0-beta.1). It is not applicable to master, so it does not need to be ported.
***
related #263#issuecomment-395109222
BREAKING CHANGE: For 0.19.0 errors from reducers are no longer caught and console.error logged, instead they are just rethrown as before. This was a temporary workaround for a bug in rxjs where it would silently swallow errors. That bug has been fixed in 5.5.6+, so it is highly recommended you use _at least_ rxjs@5.5.6+ with this version of redux-observable. However, redux-observable is close to reaching 1.0.0-final which will require rxjs v6 and redux v4, if you'd like to start upgrading to it now you can use redux-observable@next (as of this writing 1.0.0-beta.1)
I thought about bumping …
=> fix(errors): errors from reducers are no longer caught and logged, instead are rethrown

index.d.ts
Defaulting to void IMO doesn't make sense because why would someone use redux if they don't have any state at all. Instead, a default of `any` means they can choose to live wild if they'd rather not type their store's state.
I also renamed the type param names so that they're more friendly in IDEs since having four type params with single letters is confusing otherwise.
=> fix(typings): Epic type parameter for State (third type param) now defaults to any instead of void

docs/basics/Epics.md
Fixes typo: `StateOverable` -> `StateObservable`.
=> docs(Epics.md) Fix typo

MIGRATION.md
"is still be setup" > "is still being setup"
=> docs(migration.md): fix typo

package.json, webpack.config.babel.js
This should get our tests back to green.
--
For those interested in digging, our tests were broken because of a change in webpack-cli, just had to upgrade: https://github.com/webpack/webpack-cli/issues/607
=> chore(webpack): update webpack, and fix babel-loader preset to be env

src/createEpicMiddleware.js, test/createEpicMiddleware-spec.js
fixes #624
Since we use the same queueScheduler that other people's app code might also use, we would get different behavior if the rootEpic is passed to `epicMiddlweare.run(rootEpic)` inside an already running queueScheduler task. Before this PR we incorrectly relief on the fact that almost always this wouldn't happen, but it can. If it does, redux-observable won't subscribe to the rootEpic soon enough--it'll be deferred until the current queue task returns, potentially missing actions.
RxJS doesn't currently publicly export QueueScheduler constructor nor QueueAction, so we reach in using arguably private APIs.
@benlesh this is doing naughty things, reaching into (currently) private APIs. If you have a moment to give this a quick once over, lmk if you have alternative suggestions. If no …
=> fix(createEpicMiddleware): Don't share a scheduler queue with anyone else's RxJS code

gulpfile.babel.js, package.json
Older versions of gulp used a now deprecated npm package called [natives](npmjs.com/package/natives) which did naughty things and broke our build in newer Node.
https://travis-ci.org/redux-observable/redux-observable/jobs/524268610
=> chore(gulp): update gulp to 4.0 to fix build

src/createEpicMiddleware.js
It is bad form to mix ES Module `import`s and CommonJS `require`s. It also causes problems when using Rollup, because it skips CommonJS module resolution when it encounters ES Module syntax. [See here](https://github.com/rollup/rollup/issues/1058#issuecomment-254187433).
=> fix(build): Don't mix ES Module and CommonJS syntax

.eslintrc, package-lock.json, package.json, src/combineEpics.ts, src/createEpicMiddleware.ts, test/operators-spec.ts
BREAKING CHANGE: Uses typescript 4.2.2 and tslib 2.1.0 (same libs as rxjs 7). @typescript-eslint/eslint-plugin and @typescript-eslint/parser has been updated to 4.22.0 to run linter properly with new ts version, new troublesome linter rules added.
Closes #735
=> feat(rxjs7): add rxjs 7 compatibility

docs/api/createEpicMiddleware.md, docs/basics/Epics.md, docs/basics/SettingUpTheMiddleware.md, docs/recipes/HotModuleReplacement.md
Since `createStore` is now officially deprecated in favor to `configureStore` and we are trying to get more people to onboard to RTK, I though I'd make a docs PR in the spirit of #706 .
…
=> update docs for use with `configureStore` and show usage with Redux Toolkit

docs/basics/Epics.md
Abbreviations hide meaning and introduce friction in reading. They add no value.
This change expands "action POJO" into "plain action object".
=> Remove POJO abbreviation in basic docs
